# node-fs-browser/config.yaml
port: 3011
# Nome mais amig치vel para o n칩 visual
label: "游늭 Navegador de Arquivos"
node_type: "fsBrowser"
# Sem inputs de fluxo, o path vir치 do campo 'path' abaixo
inputs_mode: "0"
# AGORA TEM SA칈DAS DIN츽MICAS! O frontend vai gerar um handle por arquivo/pasta.
outputs_mode: "n"
# Define o campo de input para escolher a pasta
input_fields:
  - name: "path" # Nome sem칙ntico que o frontend (SelectorControl) usar치
    type: "selector" # Tipo que o frontend renderizar치 como seletor