# node-empty-latent-image/config.yaml
port: 3005
label: "🔳 Imagem Latente Vazia"
node_type: "emptyLatentImage"
inputs_mode: "1" # Precisa de width/height/batch, talvez venham de outros nodes
outputs_mode: "1" # Saída com o latent vazio (ou info sobre ele)
# Os campos abaixo não são lidos pelo core atualmente, mas deixamos por histórico
name: "node-empty-latent-image"
description: "Node that creates a blank 'canvas' (latent image) for KSampler."
version: "0.1.0"
max_width: 16384
max_height: 16384