port: 3010
label: "🔢 Valor Fixo"
node_type: "fixedValue"
inputs_mode: "0"
outputs_mode: "n"
initial_outputs_count: 1
# Define o campo de input aqui
input_fields:
  - name: "value" # Nome que o backend/frontend pode usar
    type: "text"  # Tipo do input